### ISSUE TITLE
Add error case when the db is empty

### ISSUE THREAD

**Issue by DjalimSimaila** [ThomasRubini/SAE-A2-TruthInquiry#87]

**Comment by ThomasRubini** [comment]
could you give precisions on this ?

**Comment by DjalimSimaila** [comment]
Currently when the database is empty, the server launch just fine and clients can go on the site. There should be a message on the client side that the site is undergoing some sort of maintenance and that the game cannot be played, and the server side should detect and log that the minimal needed data to play the game are not met and should be added asap.
