### ISSUE TITLE
Add a way to configure server hosting information

### ISSUE THREAD

**Issue by AudricV** [ThomasRubini/SAE-A2-TruthInquiry#92]
This would be very useful for the legal mentions and the privacy policy pages, as this would allow people hosting game instances to precise and update in an easy way legal information, instead of editing HTML pages manually and having to stash or commit these changes, when applying the latest changes from the repository on their instance.

**Comment by ThomasRubini** [comment]
Meh. it would be helpful to see how other self-hostable websites handle this, because I'm not really eager to add a legal paragraph in the config next to things like DB credentials

**Comment by ThomasRubini** [comment]
Maybe a second configuration would be a solution ?

**Comment by AudricV** [comment]
Fixed in #150.
