### ISSUE TITLE
Serve minified web contents?

### ISSUE THREAD

**Issue by AudricV** [ThomasRubini/SAE-A2-TruthInquiry#93]
Flask serves currently HTML, CSS and JavaScript without minification. This could cause bandwidth issues if the game is used at a large scale.

Should we minimize all web contents or only a specific content type (HTML, CSS or JavaScript)? If yes, should we do so only for production or everywhere?

**Comment by ThomasRubini** [comment]
We should first chck if Flask automatically does this in production mode
